export type PlayerSystem = { name: string; games: string[] };

export const playerCategories: Record<string, PlayerSystem[]> = {
  adventure: [
    { name:"Dragonbane（龍與魔）", games:["無題團"] },
    { name:"Lamentations of the Flame Princess（火焰公主的悲嘆）", games:["水晶洞窟與孩子","Better than any man","雪山"] },
    { name:"Dungeon World（地城世界）", games:["灼紅之日的恩惠"] },
    { name:"Castles & Crusades（城堡與遠征）", games:["龍蛋"] },
    { name:"Mutants & Masterminds", games:["自由市"] },
    { name:"Savage Worlds（野蠻世界）", games:["98龍在香港"] },
    { name:"忍帕拉", games:["山上之城"] },
    { name:"7th Sea（七海）", games:["無題團"] },
    { name:"Symbaroum（辛伯隆）", games:["應許之地"] },
    { name:"FATE Core", games:["禁酒令時期美國黑幫","時空調查局"] },
    { name:"FATE Fantasy", games:["齊楚瓦大陸"] },
    { name:"忍神", games:["友情的前方","Count Zero"] },
    { name:"魔眼傳奇", games:["無題團"] },
    { name:"午夜騎士", games:["無題團"] },
    { name:"獵魔士", games:["願諸位一夜平安"] },
    { name:"Cyberpunk Red（賽博龐克：紅）", games:["烏托邦公寓"] },
    { name:"Pathfinder 2（尋路者2）", games:["瘟疫石之殞"] },
    { name:"QUEST", games:["無題團"] },
    { name:"7Wander", games:["復仇女神號"] },
    { name:"Broken Tales（破滅奇談）", games:["篇名忘記了"] },
    { name:"Fabula Ultima（最終物語）", games:["無題團"] },
    { name:"Cosmere RPG（寰宇RPG）", games:["橋九隊"] },
    { name:"Masks（蒙面少俠）", games:["蛛網遍佈象牙港"] },
    { name:"動漫心", games:["天啟四騎士"] },
    { name:"真龍轉生", games:["無題團"] },
    { name:"Blades in the Dark（暗夜冷鋒）", games:["無題團"] },
    { name:"Dungeons & Dragons 3r", games:["布倫威爾紀行","失蹤的村民"] },
    { name:"Dungeons & Dragons 5e", games:["墜入阿弗納斯","湮滅之墓","歡迎來到煉獄","布倫威爾紀行","風暴王之雷霆","法印城武器屋","凡戴爾的失落礦坑","梅拉藝術學院","小小德魯伊試煉","Stories of Han Caravan","Golden Ring","男孩與＿＿","幽靈小販","藍色巷弄","黎明追逐者","終焉海灣","壽司或牛排？","冬日璀璨","時之終末","無限環團","野獸","疑問之旅","無光城塞","冰峰之龍","行屍詭夜","浩劫殘陽","謙和之森","豐盛之谷","龍后的寶藏","冰風谷","斯特拉德的革命","公主計畫：環團","墮神之井","卡路里大陸","美麗之敵","午夜之前","銀盤美食之地：吐司巫師"] },
  ],
  horror: [
    { name:"Vampire: the Requiem 2", games:["無題團"] },
    { name:"Demon: The Descent", games:["無題團"] },
    { name:"Vampire: The Masquerade 5th", games:["業火焚城","無題團"] },
    { name:"Changeling: the Lost 2nd", games:["無題團"] },
    { name:"Monster and Other Childish Things", games:["老師怪怪der"] },
    { name:"死靈年代記：永遠的後日談", games:["病業之繭","貝絲歡迎派對","生死歸途","台中推廣會"] },
    { name:"Ten Candles（十燭）", games:["Year Walk"] },
    { name:"FATE of Cthulhu", games:["達貢的到來"] },
    { name:"魔女狩獵之夜", games:["救世的彌賽亞"] },
    { name:"天啟症候群2.0", games:["火的臉孔"] },
    { name:"Vaesen", games:["小事一樁"] },
    { name:"Alien（異形）", games:["諸神戰車"] },
    { name:"D&D＋CoC", games:["為什麼要玩CoC？"] },
    { name:"Fallen London（陷落倫敦）", games:["扭曲的詩人"] },
    { name:"禍不單行", games:["Cold Moon Sabbath"] },
    { name:"銀翼殺手", games:["電子幻夢"] },
    { name:"Tremulus（顫慄）", games:["反轉樂音與孩子們"] },
    { name:"Monster of the Week（本週主打怪）", games:["墮落的河神","渡劫","SCP：一間普通的IKEA"] },
    { name:"City of Mist（迷霧之都）", games:["V is for Going Viral"] },
    { name:"Bedlam Hall（狂氣莊園）", games:["苦難百貨公司"] },
    { name:"Brindlewood Bay（奶奶調查團）", games:["無題團"] },
    { name:"The Between（狹間）", games:["無題團"] },
    { name:"殭屍世界", games:["迫降當日"] },
    { name:"Call of Cthulhu 7e", games:["群星燃焰","奇妙動物園","猶格-索托斯之影","泥偶","洪偉no毒湯","奈亞拉托提普的面具","In Medias Res","Forget Me Not","地獄酒店","噬指者","原初之境","伴隨著藍色，微妙起伏的","昔日的殘影","古宅旅行團","獻祭","寂靜之音","聖瑪格莉特的怠亡","惡魔之子（上）","惡魔之子（下）","一掬塵土","陰鬱之使命","鉛毒之果","血濃於水","MOHOLE","常闇之廂","篇名忘記了","死光","平安夜","猩猩","周而復始","小瓢蟲","我將為砂為影","人間地獄","Callsign: CCC"] },
    { name:"Call of Cathulhu（喵蘇魯）", games:["生日派對","結婚戒指"] },
    { name:"Bluebeard’s Bride（藍鬍子的新娘）", games:["無題團","馬戲團"] },
  ],
  emotion: [
    { name:"夕燒小燒", games:["豪華客船與怪盜團","致未來的你：夏天","落葉中的掉落物：秋天","來自變化的贈禮：冬天","最後一片葉子"] },
    { name:"Tales from the Loop（迴路奇譚）", games:["夏篇","冬篇"] },
    { name:"Ribbon Drive", games:["無題團"] },
    { name:"少女展爛會", games:["星語降示之夜","成長的代價"] },
    { name:"Tiny Taverns（微小酒館）", games:["靈境・陶緣"] },
    { name:"Monsterhearts 2（怪物心2）", games:["最後的夏天","黃金城","無題團","萬華鏡的御澤市"] },
    { name:"Night Witches（夜襲魔女）", games:["無題團"] },
    { name:"Pasión de las Pasiones（熱情如火）", games:["我愛玫瑰大飯店","一斛珠","夕陽大燒"] },
    { name:"Urban Shadows（城市之影）", games:["台北","巴洛維亞"] },
    { name:"Urban Shadows 2e（城市之影2e）", games:["希臘"] },
    { name:"Babes in the Wood（樹海孤雛2e）", games:["無題團"] },
    { name:"Hearts of Wulin（武林知心）", games:["無題團","佳佳大廈","大廟口"] },
  ],
  party: [
    { name:"Paranoia", games:["無題團"] },
    { name:"FIASCO", games:["洛式劇本","你是隻貓貓"] },
    { name:"Sexy Battle Wizards（性感戰鬥巫師）", games:["無題團"] },
  ],
};
